# -*- coding: utf-8 -*-

"""
商店商品配置文件
用于定义商店中所有商品的详细信息和价格。

注意：SHOP_ITEMS列表仅用于数据迁移（scripts/migrate_shop_items_to_pg.py）。
商品数据已迁移到PostgreSQL（shop.shop_items表），实际使用时从数据库读取。
"""

from src.chat.features.odysseia_coin.service.coin_service import (
    PERSONAL_MEMORY_ITEM_EFFECT_ID,
    WORLD_BOOK_CONTRIBUTION_ITEM_EFFECT_ID,
    COMMUNITY_MEMBER_UPLOAD_EFFECT_ID,
    DISABLE_THREAD_COMMENTOR_EFFECT_ID,
    BLOCK_THREAD_REPLIES_EFFECT_ID,
    ENABLE_THREAD_COMMENTOR_EFFECT_ID,
    ENABLE_THREAD_REPLIES_EFFECT_ID,
    SELL_BODY_EVENT_SUBMISSION_EFFECT_ID,
    CLEAR_PERSONAL_MEMORY_ITEM_EFFECT_ID,
    VIEW_PERSONAL_MEMORY_ITEM_EFFECT_ID,
)

# SHOP_ITEMS列表仅用于数据迁移，实际商品数据存储在PostgreSQL的shop.shop_items表中
SHOP_ITEMS = [
    # name, description, price, category, target, effect_id
    (
        "枯萎向日葵",
        "购买后类脑娘不会再暖你的帖子",
        0,
        "物品-给自己",
        "self",
        DISABLE_THREAD_COMMENTOR_EFFECT_ID,
    ),
    (
        "告示牌",
        "上面写着禁止通行,购买后类脑娘不会在你的帖子下面对话",
        0,
        "物品-给自己",
        "self",
        BLOCK_THREAD_REPLIES_EFFECT_ID,
    ),
    (
        "魔法向日葵",
        "神奇的魔法向日葵!购买后类脑娘又会暖你的帖子了,友谊的魔法!。",
        10,
        "物品-给自己",
        "self",
        ENABLE_THREAD_COMMENTOR_EFFECT_ID,
    ),
    (
        "通行许可",
        "一张官方签发的许可,购买后类脑娘可以在你的帖子下对话.并且可以设置类脑娘的活跃时间哦",
        10,
        "物品-给自己",
        "self",
        ENABLE_THREAD_REPLIES_EFFECT_ID,
    ),
    (
        "名片",
        "输入你的信息,并解锁与类脑娘的专属长期记忆,让她真正地记住你。",
        100,
        "物品-给自己",
        "self",
        PERSONAL_MEMORY_ITEM_EFFECT_ID,
    ),
    (
        "黑衣人的记忆消除器",
        "“看这里。”咔嚓一声，一道闪光之后，类脑娘会忘记所有关于你的个人记忆。别担心，这玩意不防墨镜，但也许能防止你社会性死亡。",
        200,
        "物品-给自己",
        "self",
        CLEAR_PERSONAL_MEMORY_ITEM_EFFECT_ID,
    ),
    (
        "午后闲谈",
        "阳光正好，不如和她闲聊一会儿？她会告诉你，在你们相处的这段时间里，她悄悄记下的，关于你的那些印象与回忆。",
        50,
        "物品-给自己",
        "self",
        VIEW_PERSONAL_MEMORY_ITEM_EFFECT_ID,
    ),
    (
        "知识纸条",
        "写下你对社区的了解（仅限无关社区成员的信息），帮助类脑娘更好地认识世界。",
        0,
        "物品-贡献",
        "self",
        WORLD_BOOK_CONTRIBUTION_ITEM_EFFECT_ID,
    ),
    (
        "社区成员档案上传",
        "上传其他社区成员的档案信息，上传的信息将被正确识别为社区成员。",
        100,
        "物品-贡献",
        "self",
        COMMUNITY_MEMBER_UPLOAD_EFFECT_ID,
    ),
    (
        "拉皮条",
        "给卖屁股的大家提供更多工作机会吧!",
        0,
        "物品-贡献",
        "self",
        SELL_BODY_EVENT_SUBMISSION_EFFECT_ID,
    ),
    # 童年零食系列
    ("巧克力", "香浓的巧克力，苦香苦香的~", 8, "给类脑娘买点好吃的!", "self", None),
    ("曲奇饼干", "酥脆的饼干，咔嚓咔嚓！", 5, "给类脑娘买点好吃的!", "self", None),
    ("棒棒糖", "阿尔卑斯棒棒糖，甜甜的！", 8, "给类脑娘买点好吃的!", "self", None),
    ("薯片", "脆脆的薯片，追剧必备！", 10, "给类脑娘买点好吃的!", "self", None),
    ("棉花糖", "软绵绵的棉花糖，像云朵一样！", 7, "给类脑娘买点好吃的!", "self", None),
    # 精品系列
    (
        "珍珠奶茶",
        "甜甜的珍珠奶茶，喝一口就幸福啦~",
        60,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    (
        "疯狂星期四!",
        "香喷喷的炸鸡，大口吃肉才过瘾！",
        50,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    ("汉堡", "大大的汉堡，一口咬下去超满足！", 70, "给类脑娘买点好吃的!", "self", None),
    ("三明治", "健康的三明治，营养又好吃！", 90, "给类脑娘买点好吃的!", "self", None),
    (
        "寿司拼盘",
        "新鲜的寿司拼盘，日料控必吃！",
        100,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    # 豪华系列
    ("火锅套餐", "热辣辣的火锅，涮涮涮！", 120, "给类脑娘买点好吃的!", "self", None),
    (
        "北京烤鸭",
        "皮脆肉嫩的烤鸭，卷起来吃！",
        130,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    ("蛋糕", "甜甜的蛋糕，过生日必备！", 150, "给类脑娘买点好吃的!", "self", None),
    (
        "牛排",
        "滋滋作响的牛排，五分熟刚刚好！",
        180,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    (
        "海鲜自助!",
        "超豪华的海鲜自助! 你要请我吃嘛,你真好! ",
        200,
        "给类脑娘买点好吃的!",
        "self",
        None,
    ),
    # 童年礼物系列
    (
        "明信片",
        "旅途中随手买的明信片，记录美好回忆",
        3,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    (
        "向日葵",
        "代表阳光的花朵，和类脑娘很配吧？",
        8,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    ("小发夹", "可爱的小发夹，戴上更萌啦！", 5, "给类脑娘买点礼物!", "self", None),
    ("贴纸", "可爱的贴纸，贴哪里都好看！", 8, "给类脑娘买点礼物!", "self", None),
    ("钥匙扣", "可爱的钥匙扣，随身携带的小确幸", 10, "给类脑娘买点礼物!", "self", None),
    # 精品礼物系列
    (
        "星空投影灯",
        "可以投射美丽星空的夜灯，浪漫又治愈",
        60,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    (
        "八音盒",
        "播放轻柔音乐的精美音乐盒，听着就想睡觉",
        70,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    (
        "毛绒玩具",
        "软乎乎的毛绒玩具，抱起来超舒服！",
        80,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    (
        "围巾",
        "温暖的围巾，冬天也不怕冷啦~",
        90,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    (
        "帽子",
        "可爱的帽子，戴上超好看！",
        100,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    # 豪华礼物系列
    ("精致手办", "可爱的手办，摆在桌上超好看~", 120, "给类脑娘买点礼物!", "self", None),
    (
        "精美相册",
        "记录美好回忆的相册，每一页都是故事",
        150,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
    ("抱枕", "抱着睡觉超舒服，软绵绵的~", 180, "给类脑娘买点礼物!", "self", None),
    ("耳环", "闪闪发光的耳环，戴上超好看！", 200, "给类脑娘买点礼物!", "self", None),
    (
        "大熊玩偶",
        "大大的熊玩偶，抱起来超舒服！",
        160,
        "给类脑娘买点礼物!",
        "self",
        None,
    ),
]
