"""add_forum_vector_tables

Revision ID: add_forum_vector_tables
Revises: d4d2d70d3faa
Create Date: 2026-03-06 07:33:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "add_forum_vector_tables"
down_revision: Union[str, Sequence[str], None] = "d4d2d70d3faa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 forum schema（如果不存在）
    op.execute("CREATE SCHEMA IF NOT EXISTS forum")

    # 创建 forum_documents 表
    op.create_table(
        "forum_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False, comment="Discord帖子ID"),
        sa.Column("thread_name", sa.Text(), nullable=False, comment="帖子标题"),
        sa.Column("author_name", sa.String(), nullable=True, comment="作者显示名称"),
        sa.Column("author_id", sa.String(), nullable=True, comment="作者Discord ID"),
        sa.Column("category_name", sa.String(), nullable=True, comment="论坛频道名称"),
        sa.Column("channel_id", sa.String(), nullable=True, comment="父频道ID"),
        sa.Column("guild_id", sa.String(), nullable=True, comment="服务器ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="帖子创建时间"),
        sa.Column(
            "created_timestamp", sa.Float(), nullable=False, comment="Unix时间戳"
        ),
        sa.Column(
            "original_content", sa.Text(), nullable=False, comment="完整原始内容"
        ),
        sa.Column(
            "source_metadata",
            sa.JSON(),
            nullable=True,
            comment="来自ChromaDB的完整元数据备份",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
        schema="forum",
    )

    # 创建 forum_chunks 表
    op.create_table(
        "forum_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_index", sa.Integer(), nullable=False, comment="分块在帖子中的序号"
        ),
        sa.Column(
            "chunk_text", sa.Text(), nullable=False, comment="这个特定文本块的内容"
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072),
            nullable=False,
            comment="此文本块的半精度嵌入向量",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["forum.forum_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="forum",
    )

    # 创建 HNSW 索引用于向量搜索
    op.create_index(
        "idx_forum_embedding_hnsw",
        "forum_chunks",
        ["embedding"],
        unique=False,
        schema="forum",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除 HNSW 索引
    op.drop_index("idx_forum_embedding_hnsw", table_name="forum_chunks", schema="forum")

    # 删除表
    op.drop_table("forum_chunks", schema="forum")
    op.drop_table("forum_documents", schema="forum")

    # ### end Alembic commands ###
