
# --------------------------------------------------------------------------------
# 服务器基础配置
# --------------------------------------------------------------------------------
server_config:
  buffer_role_name: "缓冲区"      # 新人进入时获得的临时身份组
  verified_role_name: "已验证"  # 完成基础验证或引导后获得的身份组

# --------------------------------------------------------------------------------
# 引导逻辑配置文件 (guidance_config.yaml)
# --------------------------------------------------------------------------------
# 结构说明:
# `tags` 用于定义用户可以选择的兴趣方向。
# `is_default: true` 的标签为默认标签，其路径会自动包含在所有用户的引导路径中。
# `channels` 存放普通频道的ID，`threads` 存放帖子(thread)的ID。
# --------------------------------------------------------------------------------

tags:
  - name: "默认"
    description: "服务器的核心区域，都是些不能错过的地方哦！"
    is_default: true
    channels:
      - 1393179379126767686 # 新卡速递
      - 1337107956499615744 # 答疑区
      - 1307242450300964986 # 搜索频道
      - 1234431470773338143 # 卡区bot介绍
      - 1402121015911518379 # 羁绊的开始
    threads:
      - 1365567153390227508 # 回顶区
      - 1431907913055600731 # 预设破限区
      - 1431906908478115891 # 角色卡分区：世界书

  - name: "男性向"
    description: "嘿，这里有好玩的男性向内容，快来看看吧！"
    channels:
      - 1378738606335594667 # 男性向聊天区
    threads:
      - 1374614257919987824 # 角色卡分区：男性向

  - name: "女性向"
    description: "各种女性向的好东西都在这儿~"
    channels:
      - 1378738701919850546 # 女性向聊天区
    threads:
      - 1374630459828469853 # 角色卡分区：女性向

  - name: "纯净向"
    description: "想体验纯粹美好的情感？来这里就对啦，完全纯净，没有涩涩！"
    threads:
      - 1399006747733266452 # 角色卡分区：纯净向

  - name: "深渊"
    description: "如果你喜欢探讨人性的复杂和深邃，那就来深渊看看吧，很有深度的！"
    channels:
      - 1337561613821022248 # 深渊区入口

  - name: "聊聊天"
    description: "对AI技术感兴趣？或者想看大家斗图斗模型？来这里和大家一起聊聊天吧！"
    channels:
      - 1378734700318822400 # AI杂谈
      - 1408471251260932146 # 类脑竞技场

  - name: "其他分区"
    description: "这里是创意无限的宝库！各种脑洞大开的卡片，总有一款适合你！"
    threads:
      - 1399003980805181521 # 角色卡分区：全性向
      - 1399004359731314698 # 角色卡分区：其他区
      - 1376210194887082034 # 角色卡分区：工具区

  - name: "AI绘图"
    description: "喜欢AI画画？无论是技术交流还是作品分享，这里都能满足你！"
    channels:
      - 1378743070203576432 # NSFW绘图
      - 1378742997885390973 # SFW绘图

  - name: "酒馆美化"
    description: "想让你的酒馆界面更漂亮吗？来这里寻找或分享美化方案吧！"
    threads:
      - 1431911482727207002 # 酒馆美化区

  - name: "档案馆"
    description: "想回顾服务器的经典作品吗？档案馆里收藏了过去的作品！"
    threads:
      - 1432661851644100679 # 档案馆
