# --------------------------------------------------------------------------------
# 服务器基础配置
# --------------------------------------------------------------------------------
server_config:
  buffer_role_name: "缓冲区"      # 新人进入时获得的临时身份组
  verified_role_name: "已验证"  # 完成基础验证或引导后获得的身份组

# --------------------------------------------------------------------------------
# 引导逻辑配置文件 (guidance_config.yaml)
# --------------------------------------------------------------------------------
# 结构说明:
# `tags` 用于定义用户可以选择的兴趣方向。
# `is_default: true` 的标签为默认标签，其路径会自动包含在所有用户的引导路径中。
# `channels` 存放普通频道的ID，`threads` 存放帖子(thread)的ID。
# --------------------------------------------------------------------------------

tags:
  - name: "默认"
    description: "服务器的核心区域，都是些不能错过的地方哦！"
    is_default: true
    channels:
      - 1397920536004264056 # 新卡速递 -> 每日新卡
      - 1410196354730426398 # 答疑区 -> 新手答疑
      - 1401187216851468403 # 搜索频道
      - 1410197100838387792 # 卡区bot介绍 -> 卡区Bot功能介绍
      - 1402514085475520644 # 羁绊的开始
      - 1408886655557042176 # 资讯 -> AIGC资讯
    threads:
      - 1410199670898167899 # 回顶区
      - 1402527079119061022 # 预设破限区
      - 1402526995342168179 # 角色卡分区：世界书

  - name: "男性向"
    description: "嘿，这里有好玩的男性向内容，快来看看吧！"
    channels:
      - 1401185672768913469 # 男性向聊天区 -> 男NSFW聊天区
    threads:
      - 1402526845278224475 # 角色卡分区：男性向
      - 1408895423216750712 # 混沌区档案馆

  - name: "女性向"
    description: "各种女性向的好东西都在这儿~"
    channels:
      - 1401185721317855274 # 女性向聊天区 -> 女NSFW聊天区
    threads:
      - 1402526811790774395 # 角色卡分区：女性向
      - 1408895423216750712 # 混沌区档案馆

  - name: "纯净向"
    description: "想体验纯粹美好的情感？来这里就对啦，完全纯净，没有涩涩！"
    threads:
      - 1402526880837668987 # 角色卡分区：纯净向
      - 1408895350088925416 # 纯净向档案馆

  - name: "深渊"
    description: "如果你喜欢探讨人性的复杂和深邃，那就来深渊看看吧，很有深度的！"
    channels:
      - 1408894876296151192 # 深渊区入口 -> 角色卡分区：深渊区
    thread:
      - 1408895398818611310 # 深渊区档案馆

  - name: "聊聊天"
    description: "对AI技术感兴趣？或者想看大家斗图斗模型？来这里和大家一起聊聊天吧！"
    channels:
      - 1401185811231408158 # AI杂谈
      - 1410198464431652945 # 类脑竞技场

  - name: "其他分区"
    description: "这里是创意无限的宝库！各种脑洞大开的卡片，总有一款适合你！"
    threads:
      - 1402527053097603212 # 角色卡分区：全性向
      - 1408894989618118779 # 角色卡分区：其他区
      - 1402526978304905288 # 角色卡分区：工具区

  - name: "AI绘图"
    description: "喜欢AI画画？无论是技术交流还是作品分享，这里都能满足你！"
    channels:
      - 1401186006794764390 # NSFW绘图
      - 1401185972988936273 # SFW绘图

  - name: "酒馆美化"
    description: "想让你的酒馆界面更漂亮吗？来这里寻找或分享美化方案吧！"
    threads:
      - 1408895625340256296 # 酒馆美化区